### ISSUE TITLE
kernel panic during plain to LUKS conversion

### ISSUE THREAD

**Issue by ahxxm** [johndoe31415/luksipc#7] opened 2016-04-30 08:13 UTC
An archlinux on dell xps 15 9550, with NVMe ssd, system boot with bootctl: 3 partition, /boot, /swap and /.

Steps:

- compiled luksipc on system
- boot with arch installation iso, mount, copied binary out to /root, umount.
- resize fs to free last 100MiB
- ./luksipc -d /dev/nvme0n1p3 (which is ext4 rootfs)

Then SquashfsErrors message appears and everything stopped..

**Comment by ahxxm** [comment] 2016-04-30 08:28
I append `acpi=off` to usb disk boot option and it's converting happily now.

**Comment by johndoe31415** [comment] 2016-04-30 08:54
Hello and thanks for reporting this issue.

Unfortunately, from your description I believe that luksipc is innocent of and I think this is an issue that cannot be fixed within luksipc, but lies within the kernel. My reasoning is the following: No (regular) userspace application should ever be able to create a kernel panic. Exception here is of course if the user-space administrative user uses their capabilities to insert code via modules into the kern. luksipc does nothing of that sort, however. The only thing it ever does is open block devices, create device mapper mapping and read and write back and forth between them.

I'll therefore close this issue here (since you seem to have found a viable workaoround by disabling ACPI, that's even better). However, I would encourage you to report that bug to your distribution, including the exact version of the kernel you used and the steps to reproduce it. If you have the time, it would also be interesting to use a recent vanilla kernel and see if the issue happens with that. If so, the correct addressee for the bug would be directly LKML, the Linux Kernel Mailing List.

Hope everything works as expected and thank you for taking the time to try out luksipc. Have a nice day, Joe

**Closed by johndoe31415** 2016-04-30 08:54 UTC

**Comment by ahxxm** [comment] 2016-04-30 11:53
not everything, I tried resize back and encountered another kernel panic(even with `acpi=off`), however a reboot solves this... Now my partition is fully encrypted, thank you!
